### ISSUE TITLE
Problem with NBIoT in HTTP

### ISSUE THREAD

**Issue by italobbarros** [FelixLinSY/am7020_arduino#2]
Hi, I have a problem with am7020 http.ino. This code hangs in the  "while(!modem.waitForNetwork())", what am I doing wrong?

**Comment by FelixLinSY** [comment]
> Hi, I have a problem with am7020 http.ino. This code hangs in the "while(!modem.waitForNetwork())", what am I doing wrong?

Hi @italobbarros, 
Could you please check your NBIoT SIM card is valid or not. and the mobile network is accessible.
In that state the MCU is trying to connect NBIoT network by using the specific APN and BAND parameters.
also make confirmation the dependent libraries is installed correctly.

Hope those tips would be helpful.

**Comment by italobbarros** [comment]
Hi, thanks for reply. it worked!
